# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PoliscopePlugin
                                 A QGIS plugin
 KI-basiertes Crawling von Ratsinformationssystemen der 5.000+ Planungsträger optimiert Ihre Flächensicherung und verschafft den Wissensvorsprung am Erneuerbare Energie - Markt.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-18
        copyright            : (C) 2024 by planGIS GmbH
        email                : s.wiemers@plangis.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PoliscopePlugin class from file PoliscopePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .poliscope_plugin import PoliscopePlugin
    return PoliscopePlugin(iface)
