"""
/***********************************************************
 PoliscopePlugin
                                 A QGIS plugin
 KI-basiertes Crawling von Ratsinformationssystemen der 5.000+ Planungsträger optimiert Ihre Flächensicherung und verschafft den Wissensvorsprung am Erneuerbare Energie - Markt.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
 ***********************************************************/

/***********************************************************
 *                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***********************************************************/
"""
import os
import webbrowser
from datetime import date, timedelta

from dateutil.relativedelta import relativedelta

from PyQt5 import QtWidgets, uic
from PyQt5.QtCore import QSettings, QDate
from PyQt5.QtWidgets import (
    QTabWidget, QInputDialog, QMessageBox, QLabel,
    QGroupBox, QCheckBox
)

from qgis.core import QgsRectangle, QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsProject
from qgis.utils import iface

from qgis.PyQt.QtCore import QSettings as QgisQSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication

from qgis.gui import QgsCollapsibleGroupBox

from .resources import *
from .ui.poliscope_plugin_dockwidget import PoliscopePluginDockWidget
from .ui.list_missing_api_key_error_widget import ListMissingApiKeyErrorWidget
from .ui.list_wrong_plugin_version_error_widget import ListWrongPluginVersionErrorWidget
from .ui.list_item_widget import ListItemWidget
from .ui.detail_dialog import DetailDialog
from .utils.utils import Utils
from .api.poliscopeAPI import PoliscopeAPI, ResultGroup

class PoliscopePlugin:
    "QGis Plugin Implementation"

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', f'PoliscopePlugin_{locale}.qm')

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Poliscope Plugin')
        self.toolbar = self.iface.addToolBar(u'PoliscopePlugin')
        self.toolbar.setObjectName(u'PoliscopePlugin')

        self.pluginIsActive = False
        self.dockwidget = None
        self.QGIS_PLUGIN_VERSION_UP2DATE = True

        self.results_count_focusregion = 0
        self.results_focusregion = []
        self.displayedCount_focusregion = 0

        self.results_count_search = 0
        self.results_search = []
        self.displayedCount_search = 0

        self.results_count_watchlist = 0

        self.nr = 0

        self.entityRSCodes_focusregion = []

        self.BBoxSearchClicked = False
        self.CenterSearchClicked = False

    def tr(self, message):
        return QCoreApplication.translate('PoliscopePlugin', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True, add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/poliscope_plugin/icon.png'
        self.add_action(icon_path, text=self.tr(u'Poliscope Plugin'),
                        callback=self.run, parent=self.iface.mainWindow())
        self.run()

    def onClosePlugin(self):
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Poliscope Plugin'), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run(self):
        if not self.pluginIsActive:

            if self.dockwidget is None:
                self.dockwidget = PoliscopePluginDockWidget()

            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)

            self.tabWidget = self.dockwidget.findChild(QTabWidget, "tabWidget")

            settings = QSettings()
            settings.beginGroup("PoliscopePlugin")
            api_key = settings.value("api_key", "", type=str)
            settings.endGroup()
            try:
                self.api = PoliscopeAPI(api_key=api_key)
            except Exception as e:
                print(f"Fehler beim Initialisieren der API: {e}")
                self.api = None

            #########################
            # Tab Focusregionen
            # Meetingliste

            #########################
            # Tab Suche
            #Suchanfrage
            self.leQuery_search = self.dockwidget.findChild(
                QtWidgets.QLineEdit, "leQuery_search")
            
            #Suche Filtern Box
            self.cgbSearch = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "cgbSearch")            
            ##Suchzeitraum
            self.dateBegin_search = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteBegin_search")
            self.dateEnd_search = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteEnd_search")
            ##Zeit Buttons
            self.dockwidget.pbLast30Days_search.clicked.connect(
                self.setDateLast30Days_search)
            self.dockwidget.pbNext30Days_search.clicked.connect(
                self.setDateNext30Days_search)
            self.dockwidget.pbLastYear_search.clicked.connect(
                self.setDateLastYear_search)
            self.dockwidget.pbThisYear_search.clicked.connect(
                self.setDateThisYear_search)
            ##Quellen
            self.cbTOPs_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPs_search")
            self.cbTOPBeschreibungen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPBeschreibungen_search")
            self.cbVorlagen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagen_search")
            self.cbVorlagenBeschreibungen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagenBeschreibungen_search")
            self.cbDokumente_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbDokumente_search")
            ##Verwaltungsebene
            self.cbPlanungsregionen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbPlanungsregionen_search")
            self.cbLandkreise_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbLandkreise_search")
            self.cbGemeindeverbaende_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbGemeindeverbaende_search")
            
            #Sucheinstellungen
            self.gbSucheinstellungen_search = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "gbSucheinstellungen_search")
            ##Suchmodus
            self.rbSemantisch_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbSemantisch_search")
            self.rbKeyword_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbKeyword_search")
            ##Suchtiefe
            self.rbSchnellsuche_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbSchnellsuche_search")
            self.rbTiefenrecherche_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbTiefenrecherche_search")
            self.rbUmfassend_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbUmfassend_search")
            ##Score
            self.rbPraezise_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbPraezise_search")
            self.rbAusgewogen_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbAusgewogen_search")
            self.rbBreit_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbBreit_search")

            #Sortierung
            self.cbxSortierung_search = self.dockwidget.findChild(
                QtWidgets.QComboBox, "cbxSortierung_search")
            
            #Meetings
            ## Meetingliste
            self.searchList = self.dockwidget.findChild(
                QtWidgets.QListWidget, "searchList")
            ##Anzahl der Meetings
            self.lMeetingCount_search = self.dockwidget.findChild(
                QtWidgets.QLabel, "lMeetingCount_search")
            ##Anzahl der Meetings im Vergleich zu allen Ergebnissen
            self.lblResultCount_search = self.dockwidget.findChild(
                QtWidgets.QLabel, "lblResultCount_search")
            self.pbMehrLaden_search = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbMehrLaden_search")
            self.dockwidget.clicked.connect(self.loadMore_search)

    # Die nächsten 50 Ergebnisse Laden für die Suche
    def loadMore_search(self):
        next_batch = self.results_search[self.displayedCount_search:self.displayedCount_search+50]
        self.setResultsToList(next_batch, self.searchList)
        self.displayedCount_search.setText(
            f"{self.displayedCount_search} von {len(self.results_search)} Ergebnissen"
        if self.dispayedCount_search >= len(self.results_search):
            self.pbMehrLaden_search.setVisible(False)
        )
    
    #Datumsfunktionen
    ## Datumsfunktionen für die Fokusregion
    def setCgbTitleSearch(self, dateString):
        self.cbgFocusregion.setTitle(f"Fokusregion filtern ({dateString})")

    def setDateLast30Days_focusregion(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_focusregion.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_focusregion.setDate(QDate(today.year, today.month, today.day))
        end_str = today.strftime("%d.%m.%y")
        begin_str = last_30_days.strftime("%d.%m.%y")
        self.setCgbTitleFocusregion(begin_str + " - " + end_str)

    def setDateNext30Days_focusregion(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_focusregion.setDate(QDate(today.year, today.month, today.day))
        self.dateEnd_focusregion.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        begin_str = today.strftime("%d.%m.%y")
        end_str = next_30_days.strftime("%d.%m.%y")
        self.setCgbTitleFocusregion(begin_str + " - " + end_str)

    def setDateThisYear_focusregion(self):
        today = date.today()
        self.dateBegin_focusregion.setDate(QDate(today.year, 1, 1))
        self.dateEnd_focusregion.setDate(QDate(today.year, 12, 31))
        begin_str = date(today.year, 1, 1).strftime("%d.%m.%y")
        end_str = date(today.year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleFocusregion(begin_str + " - " + end_str)

    def setDateLastYear_focusregion(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_focusregion.setDate(QDate(last_year, 1, 1))
        self.dateEnd_focusregion.setDate(QDate(last_year, 12, 31))
        begin_str = date(last_year, 1, 1).strftime("%d.%m.%y")
        end_str = date(last_year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleFocusregion(begin_str + " - " + end_str)

    ## Datumsfunktionen für die Search
    def setCbgTitleSearch(self, dateString):
        self.cgbSearch.setTtitle(f"Suche filtern ({dateString})")

    def setDateLast30Days_search(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_search.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_search.setDate(QDate(today.year, today.month, today.day))
        end_str = today.strftime("%d.%m.%y")
        begin_str = last_30_days.strftime("%d.%m.%y")
        self.setCgbTitleSearch(begin_str + " - " + end_str)
        
    def setDateNext30Days_search(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_search.setDate(
            QDate(today.year, today.month, today.day))
        self.dateEnd_search.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        begin_str = today.strftime("%d.%m.%y")
        end_str = next_30_days.strftime("%d.%m.%y")
        self.setCgbTitleSearch(begin_str + " - " + end_str)

    def setDateThisYear_search(self):
        today = date.today()
        self.dateBegin_search.setDate(QDate(today.year, 1, 1))
        self.dateEnd_search.setDate(QDate(today.year, 12, 31))
        begin_str = date(today.year, 1, 1).strftime("%d.%m.%y")
        end_str = date(today.year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleSearch(begin_str + " - " + end_str)

    def setDateLastYear_search(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_search.setDate(QDate(last_year, 1, 1))
        self.dateEnd_search.setDate(QDate(last_year, 12, 31))
        begin_str = date(last_year, 1, 1).strftime("%d.%m.%y")
        end_str = date(last_year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleSearch(begin_str + " - " + end_str)
    
    ## Datumsfunktionen für die Watchlist
    def setCbgTitleWatchlist(self, dateString):
        self.cgbWatchlist.setTitle(f"Merkliste filtern ({dateString})")

    def setDateLast30Days_watchlist(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_watchlist.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_watchlist.setDate(
            QDate(today.year, today.month, today.day))
        end_str = today.strftime("%d.%m.%y")
        begin_str = last_30_days.strftime("%d.%m.%y")
        self.setCgbTitleWatchlist(begin_str + " - " + end_str)

    def setDateNext30Days_watchlist(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_watchlist.setDate(
            QDate(today.year, today.month, today.day))
        self.dateEnd_watchlist.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        begin_str = today.strftime("%d.%m.%y")
        end_str = next_30_days.strftime("%d.%m.%y")
        self.setCgbTitleWatchlist(begin_str + " - " + end_str)

    def setDateThisYear_watchlist(self):
        today = date.today()
        self.dateBegin_watchlist.setDate(QDate(today.year, 1, 1))
        self.dateEnd_watchlist.setDate(QDate(today.year, 12, 31))
        begin_str = date(today.year, 1, 1).strftime("%d.%m.%y")
        end_str = date(today.year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleWatchlist(begin_str + " - " + end_str)

    def setDateLastYear_watchlist(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_watchlist.setDate(QDate(last_year, 1, 1))
        self.dateEnd_watchlist.setDate(QDate(last_year, 12, 31))
        begin_str = date(last_year, 1, 1).strftime("%d.%m.%y")
        end_str = date(last_year, 12, 31).strftime("%d.%m.%y")
        self.setCgbTitleWatchlist(begin_str + " - " + end_str)

    #Filling the list_itme_widget
    def setResultsToList(self, results, list_widget):
        type_map = {"meeting": "Sitzung", "proposal": "Vorlage", "document": "Dokument"}                                                                                          for result_group in results:
        for result_group in results:
            item_widget = ListItemWidget()                                                                                                                                  
            item_widget.lTitle.setText(result_group.context.entity_name)
            item_widget.lDate.setText(Utils.format_date(result_group.context.date))
            item_widget.lRISBreadcrumbs.setText(Utils.buildRISBreadcrumbs(result_group.context))
            if result_group.context.location:
                loc = result_group.context.location
                item_widget.lLocation.setText(
                    Utils.getLocationString(f"{loc['lat']}, {loc['lon']}"))
            item_widget.lScore.setText(Utils.format_score(result_group.score))
            item_widget.lChunkType.setText(type_map.get(result_group.group_type, result_group.group_type))
            if result_group.hits:
                item_widget.lHitsPreview.setText(result_group.hits[0].text[:200])
            item_widget.pbDetails.clicked.connect(
                lambda checked=False, rg=result_group: self.showDetailDialog(rg))

            container = QtWidgets.QWidget()
            container.setObjectName("container")
            layout = QtWidgets.QVBoxLayout(container)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.addWidget(item_widget)
            if self.nr % 2 == 0:
                container.setStyleSheet("background-color: #ffffff;")
            else:
                container.setStyleSheet("background-color: #eeeeee;")

            item = QtWidgets.QListWidgetItem()
            item.setSizeHint(container.sizeHint())
            list_widget.addItem(item)
            list_widget.setItemWidget(item, container)
            self.nr += 1