"""
/***********************************************************
 PoliscopePlugin
                                 A QGIS plugin
 KI-basiertes Crawling von Ratsinformationssystemen der 5.000+ Planungsträger optimiert Ihre Flächensicherung und verschafft den Wissensvorsprung am Erneuerbare Energie - Markt.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
 ***********************************************************/

/***********************************************************
 *                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***********************************************************/
"""
import os
import webbrowser
from datetime import date, timedelta, datetime

from dateutil.relativedelta import relativedelta

from PyQt5 import QtWidgets, uic
from PyQt5.QtCore import QSettings, QDate, QSize, QObject, QEvent
from PyQt5.QtWidgets import (
    QTabWidget, QInputDialog, QMessageBox, QLabel,
    QGroupBox, QCheckBox, QButtonGroup, QRadioButton
)

from qgis.core import QgsRectangle, QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsProject
from qgis.utils import iface

from qgis.PyQt.QtCore import QSettings as QgisQSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication

from qgis.gui import QgsCollapsibleGroupBox

from .resources import *
from .ui.poliscope_plugin_dockwidget import PoliscopePluginDockWidget
from .ui.list_missing_api_key_error_widget import ListMissingApiKeyErrorWidget
from .ui.list_wrong_plugin_version_error_widget import ListWrongPluginVersionErrorWidget
from .ui.list_item_widget import ListItemWidget
from .ui.detail_dialog import DetailDialog
from .utils.utils import Utils
from .api.poliscopeAPI import PoliscopeAPI, ResultGroup

class _ToolTipBlocker(QObject):
    """Consumes QEvent.ToolTip so child widgets don't inherit parent tooltips."""
    def eventFilter(self, obj, event):
        if event.type() == QEvent.ToolTip:
            return True
        return super().eventFilter(obj, event)


class PoliscopePlugin:
    "QGis Plugin Implementation"

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', f'PoliscopePlugin_{locale}.qm')

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Poliscope Plugin')
        self.toolbar = self.iface.addToolBar(u'PoliscopePlugin')
        self.toolbar.setObjectName(u'PoliscopePlugin')

        self.pluginIsActive = False
        self.dockwidget = None
        self.QGIS_PLUGIN_VERSION_UP2DATE = True

        self.results_count_focusregion = 0
        self.results_focusregion = []
        self.displayedCount_focusregion = 0
        self._focusregion_cache = {}

        self.results_count_search = 0
        self.results_search = []
        self.displayedCount_search = 0

        self.results_count_watchlist = 0
        self._session_unbookmarked = {}
        self._bookmarked_meetings = []
        self._entity_hierarchy = {}

        # Shared alternating-row counter for setResultsToList; reset to 0 before each render
        self.nr = 0

        self.entityRSCodes_focusregion = []

        self.BBoxSearchClicked = False
        self.CenterSearchClicked = False

    def tr(self, message):
        return QCoreApplication.translate('PoliscopePlugin', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True, add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(os.path.dirname(__file__), 'logo.png')
        self.add_action(icon_path, text=self.tr(u'Poliscope Plugin'),
                        callback=self.run, parent=self.iface.mainWindow())

    def onClosePlugin(self):
        self._session_unbookmarked.clear()
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False
        self.dockwidget.deleteLater()
        self.dockwidget = None

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Poliscope Plugin'), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar
        if self.dockwidget is not None:
            self.iface.removeDockWidget(self.dockwidget)
            self.dockwidget.deleteLater()
            self.dockwidget = None

    def run(self):
        if not self.pluginIsActive:

            if self.dockwidget is None:
                self.dockwidget = PoliscopePluginDockWidget()

            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.setWindowIcon(QIcon(os.path.join(os.path.dirname(__file__), 'logo.png')))

            self.tabWidget = self.dockwidget.findChild(QTabWidget, "tabWidget")

            settings = QSettings()
            settings.beginGroup("PoliscopePlugin")
            api_key = settings.value("api_key", "", type=str)
            settings.endGroup()
            if api_key:
                self.api = PoliscopeAPI(api_key=api_key)
            else:
                self.api = None

            #########################
            # Tab Fokusregionen

            self._focusregions = None
            self._focusregion_button_group = None

            self.focusregionRefButton = self.dockwidget.findChild(
                QtWidgets.QPushButton, "focusregionRefButton")
            self.focusregionRefButton.clicked.connect(
                lambda: self.btnHandlerRefresh_focusregion(force=True))

            self.focusregionList = self.dockwidget.findChild(
                QtWidgets.QListWidget, "focusregionList")
            self.lMeetingCount_focusregion = self.dockwidget.findChild(
                QtWidgets.QLabel, "lMeetingCount_focusregion")
            self.lblResultCount_focusregion = self.dockwidget.findChild(
                QtWidgets.QLabel, "lblResultCount_focusregion")
            self.pbMehrLaden_focusregion = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbMehrLaden_focusregion")
            self.pbMehrLaden_focusregion.clicked.connect(self.loadMore_focusregion)
            self.pbMehrLaden_focusregion.setVisible(False)
            self.lblResultCount_focusregion.setText("")
            self.lMeetingCount_focusregion.setText("")

            self.cbxSortierung_focusregion = self.dockwidget.findChild(
                QtWidgets.QComboBox, "cbxSortierung_focusregion")
            self.cbxSortierung_focusregion.currentIndexChanged.connect(
                self.onSortingChanged_focusregion)

            self.dateBegin_focusregion = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteBegin_focusregion")
            self.dateEnd_focusregion = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteEnd_focusregion")

            self.dockwidget.pbLast30Days_focusregion.clicked.connect(
                self.setDateLast30Days_focusregion)
            self.dockwidget.pbNext30Days_focusregion.clicked.connect(
                self.setDateNext30Days_focusregion)
            self.dockwidget.pbLastYear_focusregion.clicked.connect(
                self.setDateLastYear_focusregion)
            self.dockwidget.pbThisYear_focusregion.clicked.connect(
                self.setDateThisYear_focusregion)

            self.cbTOPs_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPs_focusregion")
            self.cbTOPBeschreibungen_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPBeschreibungen_focusregion")
            self.cbVorlagen_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagen_focusregion")
            self.cbVorlagenBeschreibungen_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagenBeschreibungen_focusregion")
            self.cbDokumente_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbDokumente_focusregion")
            self.cbPlanungsregionen_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbPlanungsregionen_focusregion")
            self.cbLandkreise_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbLandkreise_focusregion")
            self.cbGemeindeverbaende_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbGemeindeverbaende_focusregion")

            self.gbFocusregions_focusregion = self.dockwidget.findChild(
                QGroupBox, "gbFocusregions_focusregion")
            self.cgbSucheFiltern_focusregion = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "cgbSucheFiltern_focusregion")

            self.pbInKarteZentrieren_focusregion = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbInKarteZentrieren_focusregion")
            self.pbInSucheOeffnen_focusregion = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbInSucheOeffnen_focusregion")
            self.pbZentriertInSucheOeffnen_focusregion = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbZentriertInSucheOeffnen_focusregion")
            self.pbInKarteZentrieren_focusregion.clicked.connect(
                self.onInKarteZentrieren_focusregion)
            self.pbInSucheOeffnen_focusregion.clicked.connect(
                self.onInSucheOeffnen_focusregion)
            self.pbZentriertInSucheOeffnen_focusregion.clicked.connect(
                self.onZentriertInSucheOeffnen_focusregion)

            self.pbOptions_focusregion = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbOptions_focusregion")
            self.pbOptions_focusregion.clicked.connect(self.openOptions)

            self.cbNurNeuigkeiten_focusregion = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbNurNeuigkeiten_focusregion")
            self.cbNurNeuigkeiten_focusregion.toggled.connect(
                self._update_date_widgets_focusregion)

            # Default date range (used when "Nur Neuigkeiten" is unchecked)
            today_fr = date.today()
            today_fr_last_year = today_fr - relativedelta(years=1)
            today_fr_plus_two = today_fr + relativedelta(months=2)
            self.dateBegin_focusregion.setDate(
                QDate(today_fr_last_year.year, today_fr_last_year.month, today_fr_last_year.day))
            self.dateEnd_focusregion.setDate(
                QDate(today_fr_plus_two.year, today_fr_plus_two.month, today_fr_plus_two.day))
            self._update_date_widgets_focusregion(self.cbNurNeuigkeiten_focusregion.isChecked())

            #########################
            # Tab Suche

            # Suchanfrage
            self.leQuery_search = self.dockwidget.findChild(
                QtWidgets.QLineEdit, "leQuery_search")

            # Suche Filtern Box
            self.cgbSearch = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "cgbSearch")

            ## Suchzeitraum
            self.dateBegin_search = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteBegin_search")
            self.dateEnd_search = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteEnd_search")

            ## Zeit Buttons
            self.dockwidget.pbLast30Days_search.clicked.connect(
                self.setDateLast30Days_search)
            self.dockwidget.pbNext30Days_search.clicked.connect(
                self.setDateNext30Days_search)
            self.dockwidget.pbLastYear_search.clicked.connect(
                self.setDateLastYear_search)
            self.dockwidget.pbThisYear_search.clicked.connect(
                self.setDateThisYear_search)

            ## Quellen
            self.cbTOPs_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPs_search")
            self.cbTOPBeschreibungen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbTOPBeschreibungen_search")
            self.cbVorlagen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagen_search")
            self.cbVorlagenBeschreibungen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbVorlagenBeschreibungen_search")
            self.cbDokumente_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbDokumente_search")

            ## Verwaltungsebene
            self.cbPlanungsregionen_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbPlanungsregionen_search")
            self.cbLandkreise_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbLandkreise_search")
            self.cbGemeindeverbaende_search = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbGemeindeverbaende_search")

            # Sucheinstellungen
            self.gbSucheinstellungen_search = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "gbSucheinstellungen_search")

            ## Suchmodus
            self.rbSemantisch_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbSemantisch_search")
            self.rbKeyword_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbKeyword_search")
            self.gbScore_search = self.dockwidget.findChild(
                QGroupBox, "gbScore_search")
            self.rbSemantisch_search.toggled.connect(self.onSuchmodusChanged)
            self.rbKeyword_search.toggled.connect(self.onSuchmodusChanged)

            ## Suchtiefe
            self.rbSchnellsuche_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbSchnellsuche_search")
            self.rbTiefenrecherche_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbTiefenrecherche_search")
            self.rbUmfassend_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbUmfassend_search")

            ## Score
            self.rbPraezise_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbPraezise_search")
            self.rbAusgewogen_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbAusgewogen_search")
            self.rbBreit_search = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbBreit_search")

            self._tooltip_blocker = _ToolTipBlocker(self.dockwidget)
            for _rb in [
                self.rbSemantisch_search, self.rbKeyword_search,
                self.rbSchnellsuche_search, self.rbTiefenrecherche_search, self.rbUmfassend_search,
                self.rbPraezise_search, self.rbAusgewogen_search, self.rbBreit_search,
            ]:
                _rb.installEventFilter(self._tooltip_blocker)

            # Sortierung
            self.cbxSortierung_search = self.dockwidget.findChild(
                QtWidgets.QComboBox, "cbxSortierung_search")
            self.cbxSortierung_search.currentIndexChanged.connect(self.onSortingChanged)

            # Meetings
            ## Meetingliste
            self.searchList = self.dockwidget.findChild(
                QtWidgets.QListWidget, "searchList")
            ## Anzahl der Meetings
            self.lMeetingCount_search = self.dockwidget.findChild(
                QtWidgets.QLabel, "lMeetingCount_search")
            ## Anzahl der Ergebnisse vs. angezeigte
            self.lblResultCount_search = self.dockwidget.findChild(
                QtWidgets.QLabel, "lblResultCount_search")
            self.pbMehrLaden_search = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbMehrLaden_search")
            self.pbMehrLaden_search.clicked.connect(self.loadMore_search)
            self.pbMehrLaden_search.setVisible(False)
            self.lblResultCount_search.setText("")

            # BBox / Zentrum Suche Buttons
            self.searchBbSearchButton = self.dockwidget.findChild(
                QtWidgets.QPushButton, "searchBbSearchButton")
            self.searchCenterSearchButton = self.dockwidget.findChild(
                QtWidgets.QPushButton, "searchCenterSearchButton")
            self.searchBbSearchButton.clicked.connect(self.onBBoxSearchClicked)
            self.searchCenterSearchButton.clicked.connect(self.onCenterSearchClicked)

            # Options (Zahnrad)
            self.pbOptions_search = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbOptions_search")
            self.pbOptions_search.clicked.connect(self.openOptions)

            #########################
            # Tab Merkliste

            self.watchlistList = self.dockwidget.findChild(
                QtWidgets.QListWidget, "watchlistList")
            self.pbOptions_watchlist = self.dockwidget.findChild(
                QtWidgets.QPushButton, "pbOptions_watchlist")
            self.pbOptions_watchlist.clicked.connect(self.openOptions)

            self.cgbWatchlist = self.dockwidget.findChild(
                QgsCollapsibleGroupBox, "cgbWatchlist")
            self.dateBegin_watchlist = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteBegin_watchlist")
            self.dateEnd_watchlist = self.dockwidget.findChild(
                QtWidgets.QDateTimeEdit, "mteEnd_watchlist")

            self.dockwidget.pbLast30Days_watchlist.clicked.connect(
                self.setDateLast30Days_watchlist)
            self.dockwidget.pbNext30Days_watchlist.clicked.connect(
                self.setDateNext30Days_watchlist)
            self.dockwidget.pbLastYear_watchlist.clicked.connect(
                self.setDateLastYear_watchlist)
            self.dockwidget.pbThisYear_watchlist.clicked.connect(
                self.setDateThisYear_watchlist)

            self.cbGespeichert_watchlist = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbGespeichert_watchlist")
            self.cbNichtgespeichert_watchlist = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbNichtgespeichert_watchlist")

            self.cbPlanungsregionen_watchlist = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbPlanungsregionen_watchlist")
            self.cbLandkreise_watchlist = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbLandkreise_watchlist")
            self.cbGemeindeverbaende_watchlist = self.dockwidget.findChild(
                QtWidgets.QCheckBox, "cbGemeindeverbaende_watchlist")

            self.rbAlleAnzeigen_watchlist = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbAlleAnzeigen_watchlist")
            self.rbBbox_watchlist = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbBbox_watchlist")
            self.rbZentrum_watchlist = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbZentrum_watchlist")
            self.rbFokusregion_watchlist = self.dockwidget.findChild(
                QtWidgets.QRadioButton, "rbFokusregion_watchlist")

            self.wFokusregionen_watchlist = self.dockwidget.findChild(
                QtWidgets.QWidget, "wFokusregionen_watchlist")
            self.wFokusregionen_watchlist.setVisible(False)
            self._watchlist_focusregion_checkboxes = []

            self.rbFokusregion_watchlist.toggled.connect(
                self._on_geo_radio_toggled_watchlist)

            self.cbxSortierung_watchlist = self.dockwidget.findChild(
                QtWidgets.QComboBox, "cbxSortierung_watchlist")
            self.cbxSortierung_watchlist.currentIndexChanged.connect(
                self.onSortingChanged_watchlist)

            self.lMeetingCount_watchlist = self.dockwidget.findChild(
                QtWidgets.QLabel, "lMeetingCount_watchlist")
            self.watchlistRefButton = self.dockwidget.findChild(
                QtWidgets.QPushButton, "watchlistRefButton")
            self.watchlistRefButton.clicked.connect(self.btnHandlerRefresh_watchlist)

            # Enable/disable buttons depending on API key
            has_api = self.api is not None
            self.focusregionRefButton.setEnabled(has_api)
            self.watchlistRefButton.setEnabled(has_api)
            self.searchBbSearchButton.setEnabled(has_api and self.QGIS_PLUGIN_VERSION_UP2DATE)
            self.searchCenterSearchButton.setEnabled(has_api and self.QGIS_PLUGIN_VERSION_UP2DATE)

            if not has_api:
                self._show_missing_api_key(self.focusregionList)
                self._show_missing_api_key(self.searchList)
                self._show_missing_api_key(self.watchlistList)
            else:
                self._load_focusregion_radio_buttons()

                self._show_list_hint(
                    self.focusregionList,
                    "Fokusregion auswählen und <b>Liste aktualisieren</b> klicken, "
                    "um Ergebnisse zu laden.<br><br>"
                    "Fokusregionen können nur im Browser verwaltet werden: "
                    "<a href='https://poliscope.de/app/focusregions'>"
                    "poliscope.de/app/focusregions</a>"
                )
                self._show_list_hint(
                    self.searchList,
                    "Suchbegriff eingeben und <b>BBox Suche</b> oder <b>Zentrum Suche</b> klicken."
                )
                self._show_list_hint(
                    self.watchlistList,
                    "Auf <b>Liste aktualisieren</b> klicken, um die Merkliste zu laden."
                )

            # Startdatum Merkliste: letztes Jahr bis heute + 2 Monate
            today_wl = date.today()
            today_wl_last_year = today_wl - relativedelta(years=1)
            today_wl_plus_two = today_wl + relativedelta(months=2)
            self.dateBegin_watchlist.setDate(
                QDate(today_wl_last_year.year, today_wl_last_year.month, today_wl_last_year.day))
            self.dateEnd_watchlist.setDate(
                QDate(today_wl_plus_two.year, today_wl_plus_two.month, today_wl_plus_two.day))
            self.setCgbTitleWatchlist(
                today_wl_last_year.strftime("%d.%m.%y") + " - " +
                today_wl_plus_two.strftime("%d.%m.%y"))

            # Startdatum: letztes Jahr bis heute + 2 Monate
            today = date.today()
            today_last_year = today - relativedelta(years=1)
            today_plus_two_months = today + relativedelta(months=2)
            self.dateBegin_search.setDate(
                QDate(today_last_year.year, today_last_year.month, today_last_year.day))
            self.dateEnd_search.setDate(
                QDate(today_plus_two_months.year, today_plus_two_months.month, today_plus_two_months.day))
            self.setCgbTitleSearch(
                today_last_year.strftime("%d.%m.%y") + " - " + today_plus_two_months.strftime("%d.%m.%y"))

            # Restore last active tab, or open Hilfe tab on first use
            settings = QSettings()
            settings.beginGroup("PoliscopePlugin")
            last_tab = settings.value("last_tab", None)
            settings.endGroup()
            if last_tab is None:
                self.tabWidget.setCurrentIndex(3)
            else:
                self.tabWidget.setCurrentIndex(int(last_tab))
            self.tabWidget.currentChanged.connect(self._onTabChanged)

            self.pluginIsActive = True

    # BBox / Zentrum Suche
    def onBBoxSearchClicked(self):
        self.BBoxSearchClicked = True
        self.CenterSearchClicked = False
        self.btnHandlerRefresh_search()

    def onCenterSearchClicked(self):
        self.CenterSearchClicked = True
        self.BBoxSearchClicked = False
        self.btnHandlerRefresh_search()

    def _onTabChanged(self, index):
        settings = QSettings()
        settings.beginGroup("PoliscopePlugin")
        settings.setValue("last_tab", index)
        settings.endGroup()

    # Options-Dialog (API-Key eingeben)
    def openOptions(self):
        settings = QSettings()
        settings.beginGroup("PoliscopePlugin")
        current_key = settings.value("api_key", "", type=str)
        settings.endGroup()

        new_key, ok = QInputDialog.getText(
            None, "API-Key eingeben", "Bitte API-Key eingeben:", text=current_key)

        if not ok:
            return

        settings = QSettings()
        settings.beginGroup("PoliscopePlugin")
        settings.setValue("api_key", new_key)
        settings.endGroup()

        if new_key:
            test_api = PoliscopeAPI(api_key=new_key)
            api_is_working = test_api.get_qgis_plugin_version() is not None
        else:
            api_is_working = False

        if new_key and api_is_working:
            self.api = PoliscopeAPI(api_key=new_key)
            self.focusregionRefButton.setEnabled(True)
            self.watchlistRefButton.setEnabled(True)
            self.searchBbSearchButton.setEnabled(True)
            self.searchCenterSearchButton.setEnabled(True)
            for lst in [self.focusregionList, self.searchList, self.watchlistList]:
                lst.clear()
            self._load_focusregion_radio_buttons()
            self._show_list_hint(
                self.focusregionList,
                "Fokusregion auswählen und <b>Liste aktualisieren</b> klicken, "
                "um Ergebnisse zu laden.<br><br>"
                "Fokusregionen können nur im Browser verwaltet werden: "
                "<a href='https://poliscope.de/app/focusregions'>"
                "poliscope.de/app/focusregions</a>"
            )
            self._show_list_hint(
                self.searchList,
                "Suchbegriff eingeben und <b>BBox Suche</b> oder <b>Zentrum Suche</b> klicken.")
            self._show_list_hint(
                self.watchlistList,
                "Auf <b>Liste aktualisieren</b> klicken, um die Merkliste zu laden.")
            QMessageBox.information(
                None, "Erfolg", "API-Key wurde gespeichert und ist gültig!")
        elif new_key:
            QMessageBox.warning(
                None, "Warnung", "API-Key wurde gespeichert, ist aber nicht gültig. Bitte gültigen API-Key eingeben.")
        else:
            QMessageBox.critical(
                None, "Achtung", "Es wurde ein leerer API-Key gespeichert.")

    # Score-Box ausgrauen wenn Keyword-Modus aktiv
    def onSuchmodusChanged(self):
        self.gbScore_search.setEnabled(self.rbSemantisch_search.isChecked())

    # Suche ausführen
    def btnHandlerRefresh_search(self):
        if not self.api:
            return

        # Query
        q = self.leQuery_search.text().strip()
        if not q:
            self.searchList.clear()
            self._show_list_hint(
                self.searchList,
                "Bitte oben einen <b>Suchbegriff</b> eingeben."
            )
            return

        # Suchmodus
        mode = "semantic" if self.rbSemantisch_search.isChecked() else "keyword"

        # Suchtiefe → limit
        if self.rbTiefenrecherche_search.isChecked():
            limit = 250
        elif self.rbUmfassend_search.isChecked():
            limit = 500
        else:
            limit = 50

        # Score-Schwelle (nur bei semantisch relevant)
        if mode == "semantic":
            if self.rbPraezise_search.isChecked():
                score_threshold = 0.50
            elif self.rbBreit_search.isChecked():
                score_threshold = 0.20
            else:
                score_threshold = 0.35
        else:
            score_threshold = None

        # Quellen → types
        type_map = {
            self.cbTOPs_search: "agendaItemTitle",
            self.cbTOPBeschreibungen_search: "agendaItemDescription",
            self.cbVorlagen_search: "proposalTitle",
            self.cbVorlagenBeschreibungen_search: "proposalDescription",
            self.cbDokumente_search: "document",
        }
        selected_types = [v for cb, v in type_map.items() if cb.isChecked()]
        types = ",".join(selected_types) if selected_types else None

        # Verwaltungsebene → levels
        level_map = {
            self.cbPlanungsregionen_search: "pr",
            self.cbLandkreise_search: "40",
            self.cbGemeindeverbaende_search: "50,60",
        }
        selected_levels = [v for cb, v in level_map.items() if cb.isChecked()]
        levels = ",".join(selected_levels) if selected_levels else None

        # Datum
        date_from = self.dateBegin_search.date().toString("yyyy-MM-dd")
        date_to = self.dateEnd_search.date().toString("yyyy-MM-dd")

        # BBox oder Zentrum
        bbox = None
        if self.BBoxSearchClicked:
            bbox = Utils.get_current_canvas_bbox_polygon_epsg4326(self.iface)
            if bbox:
                lons = [p[0] for p in bbox]
                lats = [p[1] for p in bbox]
                bbox = f"{min(lons)},{min(lats)},{max(lons)},{max(lats)}"
        elif self.CenterSearchClicked:
            center_polygon = Utils.get_current_canvas_bbox_center_epsg4326(self.iface)
            if center_polygon:
                lons = [p[0] for p in center_polygon]
                lats = [p[1] for p in center_polygon]
                bbox = f"{min(lons)},{min(lats)},{max(lons)},{max(lats)}"

        # Ladeindikator einschalten
        QApplication.setOverrideCursor(Qt.WaitCursor)
        self.searchBbSearchButton.setEnabled(False)
        self.searchCenterSearchButton.setEnabled(False)

        try:
            result_groups, map_points, meta = self.api.search(
                q=q,
                mode=mode,
                types=types,
                bbox=bbox,
                levels=levels,
                date_from=date_from,
                date_to=date_to,
                limit=limit,
                score_threshold=score_threshold
            )
        finally:
            QApplication.restoreOverrideCursor()
            self.searchBbSearchButton.setEnabled(True)
            self.searchCenterSearchButton.setEnabled(True)

        if result_groups is None:
            return

        # Ergebnisse speichern und Liste zurücksetzen
        self.results_search = result_groups
        self.displayedCount_search = 0
        self.nr = 0
        self.searchList.clear()

        # Sortieren und erste 50 anzeigen
        sorted_results = self.sortResults(self.results_search)
        first_batch = sorted_results[:50]
        self.setResultsToList(first_batch, self.searchList)
        self.displayedCount_search = len(first_batch)

        # Anzahl-Label aktualisieren
        total = len(self.results_search)
        if total == 0:
            self.lMeetingCount_search.setText("Keine Sitzungen gefunden")
        elif total == 1:
            self.lMeetingCount_search.setText("1 Sitzung gefunden")
        else:
            self.lMeetingCount_search.setText(f"{total} Sitzungen gefunden")

        self.lblResultCount_search.setText(
            f"{self.displayedCount_search} von {total} Ergebnissen")

        # "Mehr laden" einblenden wenn nötig
        if total > 50:
            self.pbMehrLaden_search.setVisible(True)
            self.pbMehrLaden_search.setEnabled(True)
        else:
            self.pbMehrLaden_search.setVisible(False)

    # Sofort neu sortieren wenn Sortierung geändert wird
    def onSortingChanged(self):
        if not self.results_search:
            return
        self.nr = 0
        self.searchList.clear()
        sorted_results = self.sortResults(self.results_search)
        first_batch = sorted_results[:self.displayedCount_search or 50]
        self.setResultsToList(first_batch, self.searchList)

    # Ergebnisse nach aktueller Sortierung sortieren
    def sortResults(self, results):
        sort_text = self.cbxSortierung_search.currentText()
        if sort_text == "Datum (neueste zuerst)":
            return sorted(results,
                key=lambda rg: rg.context.date or "", reverse=True)
        elif sort_text == "Datum (älteste zuerst)":
            return sorted(results,
                key=lambda rg: rg.context.date or "")
        return results  # "Relevanz" — API-Reihenfolge beibehalten

    # Die nächsten 50 Ergebnisse laden
    def loadMore_search(self):
        sorted_results = self.sortResults(self.results_search)
        next_batch = sorted_results[
            self.displayedCount_search:self.displayedCount_search + 50]
        self.setResultsToList(next_batch, self.searchList)
        self.displayedCount_search += len(next_batch)

        total = len(self.results_search)
        self.lblResultCount_search.setText(
            f"{self.displayedCount_search} von {total} Ergebnissen")

        if self.displayedCount_search >= total:
            self.pbMehrLaden_search.setVisible(False)

    # Datumsfunktionen für die Fokusregion
    def setCgbTitleFocusregion(self, dateString):
        self.cgbSucheFiltern_focusregion.setTitle(f"Suche filtern ({dateString})")

    def setDateLast30Days_focusregion(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_focusregion.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_focusregion.setDate(QDate(today.year, today.month, today.day))
        self.setCgbTitleFocusregion(
            last_30_days.strftime("%d.%m.%y") + " - " + today.strftime("%d.%m.%y"))

    def setDateNext30Days_focusregion(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_focusregion.setDate(QDate(today.year, today.month, today.day))
        self.dateEnd_focusregion.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        self.setCgbTitleFocusregion(
            today.strftime("%d.%m.%y") + " - " + next_30_days.strftime("%d.%m.%y"))

    def setDateThisYear_focusregion(self):
        today = date.today()
        self.dateBegin_focusregion.setDate(QDate(today.year, 1, 1))
        self.dateEnd_focusregion.setDate(QDate(today.year, 12, 31))
        self.setCgbTitleFocusregion(
            date(today.year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(today.year, 12, 31).strftime("%d.%m.%y"))

    def setDateLastYear_focusregion(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_focusregion.setDate(QDate(last_year, 1, 1))
        self.dateEnd_focusregion.setDate(QDate(last_year, 12, 31))
        self.setCgbTitleFocusregion(
            date(last_year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(last_year, 12, 31).strftime("%d.%m.%y"))

    # Datumsfunktionen für die Suche
    def setCgbTitleSearch(self, dateString):
        self.cgbSearch.setTitle(f"Suche filtern ({dateString})")

    def setDateLast30Days_search(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_search.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_search.setDate(QDate(today.year, today.month, today.day))
        self.setCgbTitleSearch(
            last_30_days.strftime("%d.%m.%y") + " - " + today.strftime("%d.%m.%y"))

    def setDateNext30Days_search(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_search.setDate(QDate(today.year, today.month, today.day))
        self.dateEnd_search.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        self.setCgbTitleSearch(
            today.strftime("%d.%m.%y") + " - " + next_30_days.strftime("%d.%m.%y"))

    def setDateThisYear_search(self):
        today = date.today()
        self.dateBegin_search.setDate(QDate(today.year, 1, 1))
        self.dateEnd_search.setDate(QDate(today.year, 12, 31))
        self.setCgbTitleSearch(
            date(today.year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(today.year, 12, 31).strftime("%d.%m.%y"))

    def setDateLastYear_search(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_search.setDate(QDate(last_year, 1, 1))
        self.dateEnd_search.setDate(QDate(last_year, 12, 31))
        self.setCgbTitleSearch(
            date(last_year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(last_year, 12, 31).strftime("%d.%m.%y"))

    # Datumsfunktionen für die Watchlist
    def setCgbTitleWatchlist(self, dateString):
        self.cgbWatchlist.setTitle(f"Merkliste filtern ({dateString})")

    def setDateLast30Days_watchlist(self):
        today = date.today()
        last_30_days = today - timedelta(days=30)
        self.dateBegin_watchlist.setDate(
            QDate(last_30_days.year, last_30_days.month, last_30_days.day))
        self.dateEnd_watchlist.setDate(QDate(today.year, today.month, today.day))
        self.setCgbTitleWatchlist(
            last_30_days.strftime("%d.%m.%y") + " - " + today.strftime("%d.%m.%y"))

    def setDateNext30Days_watchlist(self):
        today = date.today()
        next_30_days = today + timedelta(days=30)
        self.dateBegin_watchlist.setDate(QDate(today.year, today.month, today.day))
        self.dateEnd_watchlist.setDate(
            QDate(next_30_days.year, next_30_days.month, next_30_days.day))
        self.setCgbTitleWatchlist(
            today.strftime("%d.%m.%y") + " - " + next_30_days.strftime("%d.%m.%y"))

    def setDateThisYear_watchlist(self):
        today = date.today()
        self.dateBegin_watchlist.setDate(QDate(today.year, 1, 1))
        self.dateEnd_watchlist.setDate(QDate(today.year, 12, 31))
        self.setCgbTitleWatchlist(
            date(today.year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(today.year, 12, 31).strftime("%d.%m.%y"))

    def setDateLastYear_watchlist(self):
        today = date.today()
        last_year = today.year - 1
        self.dateBegin_watchlist.setDate(QDate(last_year, 1, 1))
        self.dateEnd_watchlist.setDate(QDate(last_year, 12, 31))
        self.setCgbTitleWatchlist(
            date(last_year, 1, 1).strftime("%d.%m.%y") + " - " +
            date(last_year, 12, 31).strftime("%d.%m.%y"))

    # Ergebnisliste befüllen
    def setResultsToList(self, results, list_widget):
        type_map = {
            "meeting": "Sitzung",
            "proposal": "Vorlage",
            "document": "Dokument"
        }
        for result_group in results:
            item_widget = ListItemWidget()
            item_widget.lLastStatusUpdate.setVisible(False)
            item_widget.lTitle.setText(result_group.context.entity_name)
            item_widget.lDate.setText(Utils.format_date(result_group.context.date))
            item_widget.lRISBreadcrumbs.setText(Utils.buildRISBreadcrumbs(result_group.context))
            if result_group.context.location:
                loc = result_group.context.location
                lat, lon = loc['lat'], loc['lon']
                loc_html = Utils.getLocationString(f"{lat}, {lon}")
                item_widget.lLocation.setText(
                    f"<a href='geo:{lat},{lon}' style='color:inherit;text-decoration:none;'>"
                    f"{loc_html}</a>")
                item_widget.lLocation.setOpenExternalLinks(False)
                item_widget.lLocation.linkActivated.connect(
                    lambda href, _lat=lat, _lon=lon:
                        self._zoom_to_point(_lat, _lon))
            item_widget.lScore.setText(Utils.format_score(result_group.score))
            item_widget.lChunkType.setText(
                type_map.get(result_group.group_type, result_group.group_type))
            if result_group.hits:
                hit = result_group.hits[0]
                item_widget.lHitsPreview.setTextFormat(Qt.RichText)
                item_widget.lHitsPreview.setText(
                    Utils.build_highlighted_text(hit.text, hit.highlights))
            item_widget.pbDetails.clicked.connect(
                lambda checked=False, rg=result_group: self.showDetailDialog(rg))

            # RIS-URL aus dem Kontext holen (je nach Typ)
            if result_group.group_type == "meeting" and result_group.context.meeting:
                ris_url = result_group.context.meeting.get('url')
            elif result_group.group_type == "proposal" and result_group.context.proposal:
                ris_url = result_group.context.proposal.get('url')
            elif result_group.group_type == "document" and result_group.context.document:
                ris_url = result_group.context.document.get('url')
            else:
                ris_url = None

            if ris_url:
                item_widget.pbOpenRIS.clicked.connect(
                    lambda checked=False, url=ris_url: webbrowser.open(url))
            else:
                item_widget.pbOpenRIS.setEnabled(False)

            # Poliscope Web-URL
            entity_id = result_group.context.entity_id
            item_id = result_group.group_key.split(":", 1)[1] if ":" in result_group.group_key else ""
            if result_group.group_type == "meeting" and entity_id and item_id:
                web_url = f"https://poliscope.de/app/entity/{entity_id}/meeting/{item_id}"
                if result_group.hits and result_group.hits[0].agenda_item_id:
                    web_url += f"/agenda-item/{result_group.hits[0].agenda_item_id}"
                item_widget.pbWeb.clicked.connect(
                    lambda checked=False, url=web_url: webbrowser.open(url))
            elif result_group.group_type == "proposal" and entity_id and item_id:
                web_url = f"https://poliscope.de/app/entity/{entity_id}/proposal/{item_id}"
                item_widget.pbWeb.clicked.connect(
                    lambda checked=False, url=web_url: webbrowser.open(url))
            else:
                item_widget.pbWeb.setEnabled(False)

            # Merkliste (nur für Sitzungen)
            if result_group.group_type == "meeting" and result_group.context.meeting:
                meeting_id = result_group.context.meeting.get('id')
                is_bookmarked = bool(result_group.context.meeting.get('bookmarks'))
                item_widget.pbBookmark.setChecked(is_bookmarked)
                item_widget.pbBookmark.clicked.connect(
                    lambda checked=False, mid=meeting_id, btn=item_widget.pbBookmark:
                        self.bookmarkButtonPressed(mid, btn))
            else:
                item_widget.pbBookmark.setEnabled(False)

            container = QtWidgets.QWidget()
            container.setObjectName("container")
            layout = QtWidgets.QVBoxLayout(container)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.addWidget(item_widget)
            if self.nr % 2 == 0:
                container.setStyleSheet("background-color: #ffffff;")
            else:
                container.setStyleSheet("background-color: #eeeeee;")

            item = QtWidgets.QListWidgetItem()
            item.setSizeHint(container.sizeHint())
            list_widget.addItem(item)
            list_widget.setItemWidget(item, container)
            self.nr += 1

    def bookmarkButtonPressed(self, meeting_id, button):
        if button.isChecked():
            self.api.add_bookmarked_meeting(meeting_id)
        else:
            self.api.remove_bookmarked_meeting(meeting_id)

    def _load_focusregion_radio_buttons(self):
        focusregions, _ = self.api.get_focusregions(limit=500, detail="standard")
        if focusregions:
            self._populate_focusregion_radio_buttons(focusregions)
            self._focusregions = self._deduped_focusregions

    def btnHandlerRefresh_focusregion(self, force=False):
        if not self.api:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        try:
            # Load focusregions if not yet cached
            if self._focusregions is None:
                focusregions, _ = self.api.get_focusregions(limit=500, detail="standard")
                if not focusregions:
                    return
                self._populate_focusregion_radio_buttons(focusregions)
                self._focusregions = self._deduped_focusregions

            # Get selected focusregion
            fr = self._get_selected_focusregion()
            if not fr:
                return

            nur_neuigkeiten = self.cbNurNeuigkeiten_focusregion.isChecked()
            last_visit = next(
                (m.get('lastVisit') for m in (fr.team or []) if m.get('lastVisit')), None)
            cache_key = (fr.id, nur_neuigkeiten)

            if force:
                self._focusregion_cache.pop((fr.id, True), None)
                self._focusregion_cache.pop((fr.id, False), None)

            if cache_key in self._focusregion_cache:
                result_groups = self._focusregion_cache[cache_key]
            else:
                new_since = last_visit if (nur_neuigkeiten and last_visit) else None
                result_groups, _, _ = self.api.get_focusregion_results(fr.id, new_since=new_since)
                if result_groups is not None:
                    self._focusregion_cache[cache_key] = result_groups
        finally:
            QApplication.restoreOverrideCursor()

        if result_groups is None:
            return

        # Client-side filter + sort
        filtered = self._filter_focusregion_results(result_groups)
        self.results_focusregion = filtered
        self.displayedCount_focusregion = 0
        self.nr = 0
        self.focusregionList.clear()

        sorted_results = self.sortResults_focusregion(filtered)
        first_batch = sorted_results[:50]
        self.setResultsToList(first_batch, self.focusregionList)
        self.displayedCount_focusregion = len(first_batch)

        total = len(filtered)
        if total == 0:
            if nur_neuigkeiten:
                lv_display = ""
                if last_visit:
                    try:
                        lv_display = datetime.strptime(
                            last_visit[:10], '%Y-%m-%d').strftime('%d.%m.%Y')
                    except Exception:
                        pass
                fr_name = fr.name or fr.id
                lv_part = f" am <b>{lv_display}</b>" if lv_display else ""
                self._show_list_hint(
                    self.focusregionList,
                    f"Keine Neuigkeiten seit dem letzten Besuch{lv_part} "
                    f"in <b>{fr_name}</b>.<br><br>"
                    f"Den Haken bei <b>Nur Neuigkeiten</b> entfernen, "
                    f"um alle Ergebnisse im ausgewählten Zeitraum zu sehen.<br><br>"
                    f"Mit <b>Suchbegriff öffnen</b> den Suchbegriff der Fokusregion "
                    f"in der Suche öffnen um erweiterte Einstellungen nutzen."
                )
                self.lMeetingCount_focusregion.setText("")
                self.lblResultCount_focusregion.setText("")
                self.pbMehrLaden_focusregion.setVisible(False)
                return
            self.lMeetingCount_focusregion.setText("Keine Ergebnisse gefunden")
        elif total == 1:
            self.lMeetingCount_focusregion.setText("1 Ergebnis gefunden")
        else:
            self.lMeetingCount_focusregion.setText(f"{total} Ergebnisse gefunden")

        self.lblResultCount_focusregion.setText(
            f"{self.displayedCount_focusregion} von {total} Ergebnissen")

        if total > 50:
            self.pbMehrLaden_focusregion.setVisible(True)
            self.pbMehrLaden_focusregion.setEnabled(True)
        else:
            self.pbMehrLaden_focusregion.setVisible(False)

    def _populate_focusregion_radio_buttons(self, focusregions):
        gb = self.gbFocusregions_focusregion
        layout = gb.layout()

        # Remove existing radio buttons, keep push buttons
        for rb in gb.findChildren(QRadioButton):
            layout.removeWidget(rb)
            rb.deleteLater()

        # Temporarily remove push buttons so we can re-add them at the right row
        layout.removeWidget(self.pbInKarteZentrieren_focusregion)
        layout.removeWidget(self.pbInSucheOeffnen_focusregion)
        layout.removeWidget(self.pbZentriertInSucheOeffnen_focusregion)

        # Deduplicate by name, keeping the entry with the most recent lastVisit
        def _last_visit(fr):
            for member in (fr.team or []):
                lv = member.get('lastVisit')
                if lv:
                    return lv
            return ""

        seen = {}
        deduped = []
        for fr in focusregions:
            name = fr.name or fr.id
            if name not in seen:
                seen[name] = len(deduped)
                deduped.append(fr)
            else:
                idx = seen[name]
                if _last_visit(fr) > _last_visit(deduped[idx]):
                    deduped[idx] = fr
        focusregions = deduped
        self._deduped_focusregions = deduped

        self._focusregion_button_group = QButtonGroup(gb)
        for i, fr in enumerate(focusregions):
            row = i // 2
            col = i % 2
            new_count = next((m.get('newResultsCount') or 0 for m in (fr.team or [])), 0)
            label = fr.name or fr.id
            label = f"{label} (neu: {new_count})"
            # Add last-visit date from the first team member that has one
            last_visit_str = _last_visit(fr)
            if last_visit_str:
                try:
                    lv_dt = datetime.strptime(last_visit_str[:10], '%Y-%m-%d')
                    label += f"\nzuletzt aktualisiert: {lv_dt.strftime('%d.%m.%Y')}"
                except Exception:
                    pass
            rb = QRadioButton(label, gb)
            rb.setProperty("focusregion_id", fr.id)
            self._focusregion_button_group.addButton(rb, i)
            layout.addWidget(rb, row, col)
            if i == 0:
                rb.setChecked(True)

        # Re-add push buttons at the row after the last radio row
        last_radio_row = max(0, (len(focusregions) - 1) // 2)
        button_row = last_radio_row + 1
        layout.addWidget(self.pbInKarteZentrieren_focusregion, button_row, 0, 1, 2)
        layout.addWidget(self.pbInSucheOeffnen_focusregion, button_row + 1, 0)
        layout.addWidget(self.pbZentriertInSucheOeffnen_focusregion, button_row + 1, 1)

    def _get_selected_focusregion(self):
        if not self._focusregion_button_group or not self._focusregions:
            return None
        checked = self._focusregion_button_group.checkedButton()
        if not checked:
            return None
        fr_id = checked.property("focusregion_id")
        for fr in self._focusregions:
            if fr.id == fr_id:
                return fr
        return None

    def _filter_focusregion_results(self, result_groups):
        nur_neuigkeiten = self.cbNurNeuigkeiten_focusregion.isChecked()
        if not nur_neuigkeiten:
            date_from = self.dateBegin_focusregion.date().toString("yyyy-MM-dd")
            date_to = self.dateEnd_focusregion.date().toString("yyyy-MM-dd")

        type_map = {
            self.cbTOPs_focusregion: "agendaItemTitle",
            self.cbTOPBeschreibungen_focusregion: "agendaItemDescription",
            self.cbVorlagen_focusregion: "proposalTitle",
            self.cbVorlagenBeschreibungen_focusregion: "proposalDescription",
            self.cbDokumente_focusregion: "document",
        }
        selected_types = [v for cb, v in type_map.items() if cb.isChecked()]

        level_map = {
            self.cbPlanungsregionen_focusregion: ["pr"],
            self.cbLandkreise_focusregion: ["40"],
            self.cbGemeindeverbaende_focusregion: ["50", "60"],
        }
        selected_levels = []
        for cb, levels in level_map.items():
            if cb.isChecked():
                selected_levels.extend(levels)

        filtered = []
        for rg in result_groups:
            if not nur_neuigkeiten and rg.context.date:
                item_date = rg.context.date[:10]
                if item_date < date_from or item_date > date_to:
                    continue
            if selected_types and not any(
                hit.chunk_type in selected_types for hit in rg.hits
            ):
                continue
            if selected_levels and rg.context.entity_level not in selected_levels:
                continue
            filtered.append(rg)

        return filtered

    def sortResults_focusregion(self, results):
        sort_text = self.cbxSortierung_focusregion.currentText()
        if sort_text == "Datum (neueste zuerst)":
            return sorted(results, key=lambda rg: rg.context.date or "", reverse=True)
        elif sort_text == "Datum (älteste zuerst)":
            return sorted(results, key=lambda rg: rg.context.date or "")
        return results

    def loadMore_focusregion(self):
        sorted_results = self.sortResults_focusregion(self.results_focusregion)
        next_batch = sorted_results[
            self.displayedCount_focusregion:self.displayedCount_focusregion + 50]
        self.setResultsToList(next_batch, self.focusregionList)
        self.displayedCount_focusregion += len(next_batch)

        total = len(self.results_focusregion)
        self.lblResultCount_focusregion.setText(
            f"{self.displayedCount_focusregion} von {total} Ergebnissen")

        if self.displayedCount_focusregion >= total:
            self.pbMehrLaden_focusregion.setVisible(False)

    def _update_date_widgets_focusregion(self, nur_neuigkeiten_checked):
        enabled = not nur_neuigkeiten_checked
        self.dateBegin_focusregion.setEnabled(enabled)
        self.dateEnd_focusregion.setEnabled(enabled)
        self.dockwidget.pbLast30Days_focusregion.setEnabled(enabled)
        self.dockwidget.pbNext30Days_focusregion.setEnabled(enabled)
        self.dockwidget.pbLastYear_focusregion.setEnabled(enabled)
        self.dockwidget.pbThisYear_focusregion.setEnabled(enabled)
        if enabled:
            date_from = self.dateBegin_focusregion.date().toString("dd.MM.yy")
            date_to = self.dateEnd_focusregion.date().toString("dd.MM.yy")
            self.setCgbTitleFocusregion(f"{date_from} - {date_to}")
        else:
            self.cgbSucheFiltern_focusregion.setTitle("Suche filtern")

    def onInKarteZentrieren_focusregion(self):
        fr = self._get_selected_focusregion()
        if not fr or not fr.entity_ids:
            return
        ids_param = ",".join(eid.rstrip('*') for eid in fr.entity_ids)
        entities, _ = self.api.list_entities(ids=ids_param, detail="standard")
        if not entities:
            return
        locations = [e.location for e in entities if e.location]
        if not locations:
            return
        lons = [loc['lon'] for loc in locations]
        lats = [loc['lat'] for loc in locations]
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        canvas = self.iface.mapCanvas()
        transform = QgsCoordinateTransform(
            target_crs, canvas.mapSettings().destinationCrs(), QgsProject.instance())
        extent = QgsRectangle(min(lons), min(lats), max(lons), max(lats))
        if extent.isEmpty():
            cx, cy = min(lons), min(lats)
            extent = QgsRectangle(cx - 0.2, cy - 0.2, cx + 0.2, cy + 0.2)
        else:
            extent.scale(1.2)
        transformed = transform.transformBoundingBox(extent)
        canvas.setExtent(transformed)
        canvas.refresh()

    def onInSucheOeffnen_focusregion(self):
        fr = self._get_selected_focusregion()
        if not fr or not fr.query:
            return
        self.leQuery_search.setText(fr.query)
        self.tabWidget.setCurrentIndex(1)

    def onZentriertInSucheOeffnen_focusregion(self):
        fr = self._get_selected_focusregion()
        if not fr:
            return
        self.onInKarteZentrieren_focusregion()
        if fr.query:
            self.leQuery_search.setText(fr.query)
        self.tabWidget.setCurrentIndex(1)

    def onSortingChanged_focusregion(self):
        if not self.results_focusregion:
            return
        self.nr = 0
        self.focusregionList.clear()
        sorted_results = self.sortResults_focusregion(self.results_focusregion)
        first_batch = sorted_results[:self.displayedCount_focusregion or 50]
        self.setResultsToList(first_batch, self.focusregionList)

    def _show_missing_api_key(self, list_widget):
        item_widget = ListMissingApiKeyErrorWidget()
        item = QtWidgets.QListWidgetItem()
        item.setFlags(Qt.NoItemFlags)
        item.setSizeHint(item_widget.sizeHint())
        list_widget.addItem(item)
        list_widget.setItemWidget(item, item_widget)

    def _show_list_hint(self, list_widget, html_text):
        label = QLabel(html_text)
        label.setWordWrap(True)
        label.setOpenExternalLinks(True)
        label.setContentsMargins(10, 12, 10, 12)
        label.setAlignment(Qt.AlignTop | Qt.AlignLeft)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(Qt.NoItemFlags)
        item.setSizeHint(QSize(0, 110))
        list_widget.addItem(item)
        list_widget.setItemWidget(item, label)

    def showDetailDialog(self, result_group):
        dialog = DetailDialog(result_group, self.api)
        dialog.exec_()

    def _zoom_to_point(self, lat, lon):
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        canvas = self.iface.mapCanvas()
        transform = QgsCoordinateTransform(
            target_crs, canvas.mapSettings().destinationCrs(), QgsProject.instance())
        extent = QgsRectangle(lon - 0.2, lat - 0.2, lon + 0.2, lat + 0.2)
        transformed = transform.transformBoundingBox(extent)
        canvas.setExtent(transformed)
        canvas.refresh()

    def _fetch_entity_hierarchy(self, entity_ids):
        lookup = {}
        ids_to_fetch = set(entity_ids)
        while ids_to_fetch:
            ids_param = ",".join(ids_to_fetch)
            entities, _ = self.api.list_entities(ids=ids_param, detail="full", silent=True)
            if not entities:
                break
            next_ids = set()
            for e in entities:
                lookup[e.id] = e
                if e.parent and e.parent not in lookup:
                    next_ids.add(e.parent)
            ids_to_fetch = next_ids
        return lookup

    def _build_meeting_breadcrumb(self, entities):
        if not entities:
            return ""
        entity_id = entities[0].get('id', '')
        e = self._entity_hierarchy.get(entity_id)
        # Start from the entity's parent — same as context.parents in search results
        current_id = (e.parent or '') if e else ''
        parts = []
        visited = set()
        while current_id and current_id not in visited:
            visited.add(current_id)
            parent_e = self._entity_hierarchy.get(current_id)
            if parent_e:
                prefix = Utils.convertRSTypes(parent_e.level)
                parts.append(f"{prefix}: {parent_e.name}" if prefix else parent_e.name)
                current_id = parent_e.parent or ''
            else:
                break
        return " > ".join(parts)

    # Merkliste methods

    def btnHandlerRefresh_watchlist(self):
        if not self.api:
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)
        self.watchlistRefButton.setEnabled(False)
        try:
            meetings, _ = self.api.get_bookmarked_meetings(limit=500, detail="full")
        finally:
            QApplication.restoreOverrideCursor()
            self.watchlistRefButton.setEnabled(True)

        if meetings is None:
            return

        self._bookmarked_meetings = meetings

        entity_ids = {
            e.get('id') for m in meetings
            for e in m.ris.get('entities', [])
            if e.get('id')
        }
        self._entity_hierarchy = self._fetch_entity_hierarchy(entity_ids)

        self._refresh_watchlist_display()

    def _refresh_watchlist_display(self):
        combined = []
        if self.cbGespeichert_watchlist.isChecked():
            combined.extend(self._bookmarked_meetings)
        if self.cbNichtgespeichert_watchlist.isChecked():
            bookmarked_ids = {m.id for m in self._bookmarked_meetings}
            combined.extend(
                m for mid, m in self._session_unbookmarked.items()
                if mid not in bookmarked_ids)
        filtered = self._apply_watchlist_filters(combined)
        sorted_meetings = self._sort_watchlist(filtered)

        self.watchlistList.clear()
        self.setMeetingsToList_watchlist(sorted_meetings)

        total = len(sorted_meetings)
        if total == 0:
            self.lMeetingCount_watchlist.setText("Keine Sitzungen gefunden")
            if self.rbFokusregion_watchlist.isChecked():
                checked_names = [cb.text() for cb in self._watchlist_focusregion_checkboxes if cb.isChecked()]
                if not checked_names:
                    self._show_list_hint(self.watchlistList, "Bitte mindestens eine Fokusregion auswählen.")
                elif len(checked_names) == 1:
                    self._show_list_hint(
                        self.watchlistList,
                        f"In der Fokusregion <b>{checked_names[0]}</b> wurde in diesem Zeitraum nichts zur Merkliste hinzugefügt."
                    )
                else:
                    names_html = ", ".join(f"<b>{n}</b>" for n in checked_names[:-1]) + f" und <b>{checked_names[-1]}</b>"
                    self._show_list_hint(
                        self.watchlistList,
                        f"In den Fokusregionen {names_html} wurde in diesem Zeitraum nichts zur Merkliste hinzugefügt."
                    )
        elif total == 1:
            self.lMeetingCount_watchlist.setText("1 Sitzung gefunden")
        else:
            self.lMeetingCount_watchlist.setText(f"{total} Sitzungen gefunden")

    def _apply_watchlist_filters(self, meetings):
        date_from = self.dateBegin_watchlist.date().toString("yyyy-MM-dd")
        date_to = self.dateEnd_watchlist.date().toString("yyyy-MM-dd")

        level_map = {
            self.cbPlanungsregionen_watchlist: ["pr"],
            self.cbLandkreise_watchlist: ["40"],
            self.cbGemeindeverbaende_watchlist: ["50", "60"],
        }
        selected_levels = []
        for cb, levels in level_map.items():
            if cb.isChecked():
                selected_levels.extend(levels)

        geo_mode = None
        if self.rbBbox_watchlist.isChecked():
            geo_mode = "bbox"
        elif self.rbZentrum_watchlist.isChecked():
            geo_mode = "zentrum"
        elif self.rbFokusregion_watchlist.isChecked():
            geo_mode = "fokusregion"

        selected_fr_entity_ids = None
        if geo_mode == "fokusregion":
            selected_fr_entity_ids = set()
            for cb in self._watchlist_focusregion_checkboxes:
                if cb.isChecked():
                    fr_id = cb.property("focusregion_id")
                    fr = next((f for f in (self._focusregions or []) if f.id == fr_id), None)
                    if fr and fr.entity_ids:
                        selected_fr_entity_ids.update(fr.entity_ids)

        bbox_bounds = None
        if geo_mode == "bbox":
            pts = Utils.get_current_canvas_bbox_polygon_epsg4326(self.iface)
            if pts:
                lons = [p[0] for p in pts]
                lats = [p[1] for p in pts]
                bbox_bounds = (min(lons), min(lats), max(lons), max(lats))

        zentrum_entity_id = None
        if geo_mode == "zentrum":
            canvas = self.iface.mapCanvas()
            if canvas and canvas.extent():
                src_crs = canvas.mapSettings().destinationCrs()
                tgt_crs = QgsCoordinateReferenceSystem("EPSG:4326")
                transform = QgsCoordinateTransform(src_crs, tgt_crs, QgsProject.instance())
                t = transform.transformBoundingBox(canvas.extent())
                cx = (t.xMinimum() + t.xMaximum()) / 2
                cy = (t.yMinimum() + t.yMaximum()) / 2
                level_prio = {"40": 0, "50": 1, "60": 2, "pr": 3, "10": 4}
                best_e, best_score = None, None
                for e in self._entity_hierarchy.values():
                    if not e.location:
                        continue
                    elat = e.location.get('lat')
                    elon = e.location.get('lon')
                    if elat is None or elon is None:
                        continue
                    dist2 = (elon - cx) ** 2 + (elat - cy) ** 2
                    score = (level_prio.get(e.level, 5), dist2)
                    if best_score is None or score < best_score:
                        best_score = score
                        best_e = e
                zentrum_entity_id = best_e.id if best_e else None

        filtered = []
        for m in meetings:
            if m.date and (m.date[:10] < date_from or m.date[:10] > date_to):
                continue

            if selected_levels:
                entity_levels = [e.get('level', '') for e in m.ris.get('entities', [])]
                if not any(lvl in selected_levels for lvl in entity_levels):
                    continue

            if geo_mode == "fokusregion":
                if not selected_fr_entity_ids:
                    continue
                meeting_entity_ids = [e.get('id', '') for e in m.ris.get('entities', []) if e.get('id')]
                matched = False
                for mid in meeting_entity_ids:
                    # Walk up _entity_hierarchy to collect all ancestor IDs
                    ancestor_ids = set()
                    cur = mid
                    seen = set()
                    while cur and cur not in seen:
                        seen.add(cur)
                        e_h = self._entity_hierarchy.get(cur)
                        if not e_h or not e_h.parent:
                            break
                        ancestor_ids.add(e_h.parent)
                        cur = e_h.parent
                    for fid in selected_fr_entity_ids:
                        # Strip trailing * (API uses wildcards, we do prefix match)
                        fid_clean = fid.rstrip('*')
                        if mid.startswith(fid_clean) or fid_clean in ancestor_ids:
                            matched = True
                            break
                    if matched:
                        break
                if not matched:
                    continue
            elif geo_mode == "bbox":
                if bbox_bounds is not None:
                    min_lon, min_lat, max_lon, max_lat = bbox_bounds
                    lat, lon = None, None
                    if m.location:
                        lat = m.location.get('lat')
                        lon = m.location.get('lon')
                    if (lat is None or lon is None) and m.ris:
                        for e_dict in m.ris.get('entities', []):
                            e_obj = self._entity_hierarchy.get(e_dict.get('id', ''))
                            if e_obj and e_obj.location:
                                lat = e_obj.location.get('lat')
                                lon = e_obj.location.get('lon')
                                if lat is not None and lon is not None:
                                    break
                    if lat is not None and lon is not None:
                        if not (min_lon <= lon <= max_lon and min_lat <= lat <= max_lat):
                            continue
            elif geo_mode == "zentrum":
                if zentrum_entity_id:
                    meeting_entity_ids = [e.get('id', '') for e in m.ris.get('entities', []) if e.get('id')]
                    if not any(
                        mid.startswith(zentrum_entity_id) or zentrum_entity_id.startswith(mid)
                        for mid in meeting_entity_ids
                    ):
                        continue

            filtered.append(m)

        return filtered

    def _sort_watchlist(self, meetings):
        sort_text = self.cbxSortierung_watchlist.currentText()
        if sort_text == "Datum (neueste zuerst)":
            return sorted(meetings, key=lambda m: m.date or "", reverse=True)
        elif sort_text == "Datum (älteste zuerst)":
            return sorted(meetings, key=lambda m: m.date or "")
        return meetings

    def setMeetingsToList_watchlist(self, meetings):
        nr = 0
        for meeting in meetings:
            item_widget = ListItemWidget()
            item_widget.lLastStatusUpdate.setVisible(False)
            item_widget.lScore.setVisible(False)
            item_widget.lChunkType.setVisible(False)

            entities = meeting.ris.get('entities', [])
            item_widget.lRISBreadcrumbs.setText(self._build_meeting_breadcrumb(entities))

            if meeting.date:
                d = (meeting.date + 'T00:00:00')[:19]
                item_widget.lDate.setText(Utils.format_date(d))

            item_widget.lTitle.setText(entities[0].get('name', '') if entities else '')
            item_widget.lHitsPreview.setText(meeting.title or meeting.id)

            if meeting.location:
                lat = meeting.location['lat']
                lon = meeting.location['lon']
                loc_html = Utils.getLocationString(f"{lat}, {lon}")
                item_widget.lLocation.setText(
                    f"<a href='geo:{lat},{lon}' style='color:inherit;text-decoration:none;'>"
                    f"{loc_html}</a>")
                item_widget.lLocation.setOpenExternalLinks(False)
                item_widget.lLocation.linkActivated.connect(
                    lambda href, _lat=lat, _lon=lon:
                        self._zoom_to_point(_lat, _lon))

            is_bookmarked = meeting.id not in self._session_unbookmarked
            item_widget.pbBookmark.setChecked(is_bookmarked)
            item_widget.pbBookmark.clicked.connect(
                lambda checked=False, m=meeting, btn=item_widget.pbBookmark:
                    self.bookmarkButtonPressed_watchlist(m, btn))

            item_widget.pbDetails.clicked.connect(
                lambda checked=False, m=meeting: self.showDetailDialog_watchlist(m))

            entity_id = entities[0].get('id') if entities else None
            if entity_id:
                web_url = f"https://poliscope.de/app/entity/{entity_id}/meeting/{meeting.id}"
                item_widget.pbWeb.clicked.connect(
                    lambda checked=False, url=web_url: webbrowser.open(url))
            else:
                item_widget.pbWeb.setEnabled(False)

            ris_url = meeting.ris.get('url')
            if ris_url:
                item_widget.pbOpenRIS.clicked.connect(
                    lambda checked=False, url=ris_url: webbrowser.open(url))
            else:
                item_widget.pbOpenRIS.setEnabled(False)

            container = QtWidgets.QWidget()
            container.setObjectName("container")
            layout = QtWidgets.QVBoxLayout(container)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.addWidget(item_widget)
            if nr % 2 == 0:
                container.setStyleSheet("background-color: #ffffff;")
            else:
                container.setStyleSheet("background-color: #eeeeee;")

            item = QtWidgets.QListWidgetItem()
            item.setSizeHint(container.sizeHint())
            self.watchlistList.addItem(item)
            self.watchlistList.setItemWidget(item, container)
            nr += 1

    def bookmarkButtonPressed_watchlist(self, meeting, button):
        if button.isChecked():
            self.api.add_bookmarked_meeting(meeting.id)
            self._session_unbookmarked.pop(meeting.id, None)
            if not any(m.id == meeting.id for m in self._bookmarked_meetings):
                self._bookmarked_meetings.append(meeting)
        else:
            self.api.remove_bookmarked_meeting(meeting.id)
            self._session_unbookmarked[meeting.id] = meeting
            self._bookmarked_meetings = [m for m in self._bookmarked_meetings
                                         if m.id != meeting.id]
        self._refresh_watchlist_display()

    def _on_geo_radio_toggled_watchlist(self):
        is_fr = self.rbFokusregion_watchlist.isChecked()
        self.wFokusregionen_watchlist.setVisible(is_fr)
        if is_fr and not self._watchlist_focusregion_checkboxes:
            self._populate_focusregion_checkboxes_watchlist()

    def _populate_focusregion_checkboxes_watchlist(self):
        layout = self.wFokusregionen_watchlist.layout()
        if layout is None:
            layout = QtWidgets.QVBoxLayout(self.wFokusregionen_watchlist)
            layout.setContentsMargins(0, 0, 0, 0)

        self._watchlist_focusregion_checkboxes = []
        for fr in (self._focusregions or []):
            cb = QCheckBox(fr.name or fr.id, self.wFokusregionen_watchlist)
            cb.setProperty("focusregion_id", fr.id)
            cb.setChecked(True)
            layout.addWidget(cb)
            self._watchlist_focusregion_checkboxes.append(cb)

    def onSortingChanged_watchlist(self):
        if not self._bookmarked_meetings and not self._session_unbookmarked:
            return
        self._refresh_watchlist_display()

    def showDetailDialog_watchlist(self, meeting):
        dialog = DetailDialog(api=self.api)
        entities = meeting.ris.get('entities', [])
        dialog.lRISBreadcrumbs.setText(self._build_meeting_breadcrumb(entities))
        dialog.lLocation.setText(Utils.getLocationString(
            entities[0].get('name', '') if entities else ''))
        if meeting.date:
            d = (meeting.date + 'T00:00:00')[:19]
            dialog.lDate.setText(Utils.format_date(d))
        else:
            dialog.lDate.hide()

        QApplication.setOverrideCursor(Qt.WaitCursor)
        try:
            full_meeting = self.api.get_meeting(meeting.id, detail="full")
        finally:
            QApplication.restoreOverrideCursor()

        dialog._populate_meeting(full_meeting if full_meeting else meeting)
        dialog.exec_()
